'use client'
import './globals.css'
import Head from 'next/head'
import Link from 'next/link'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraProvider } from '@/components/Chakra';
const inter = Inter({ subsets: ['latin'] })
import Providers from '@/components/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest:'/manifest.webmanifest'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
     <Head>
    <link rel='manifest' href='/manifest.webmanifest' />
    <link rel='apple-touch-icon' href='/icon.png' />
    <link rel='theme-color' href='#fff' />
    
      </Head>
      <body className={inter.className}>
        <Providers>
        <ChakraProvider>
        {children}
        </ChakraProvider>
        </Providers>
        </body>
    </html>
    
  )
}
